LEFT_DWELL_TIME = 0.8
DOUBLE_DWELL_TIME = 0.8
RIGHT_DWELL_TIME = 1.0
DRAG_DWELL_TIME = 1.0

MOVEMENT_TOLERANCE = 18

DRAWING_DWELL_TIME = 0.8
DRAWING_MOVEMENT_TOLERANCE = 18

SCROLL_THRESHOLD = 18
SCROLL_COOLDOWN = 0.20
SCROLL_AMOUNT = 120

NORMAL_SMOOTH_ALPHA = 0.20
DRAWING_SMOOTH_ALPHA = 0.45

INTERPOLATION_STEPS = 8

CAMERA_INDEX = 1
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720

WINDOW_NAME = "Stage 9 - Wall Control + Drawing Mode"